In [1]:
import numpy as np

# %timeit == for one line 
%% time it === for programme         timeit function is used to check for code running  timing 

In [2]:
%timeit  arr= np.array([1,2,3,4])
#print(arr)

875 ns ± 53 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [3]:
%timeit  y = [1,2,3,4]
#print(y)

65.6 ns ± 3.13 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [4]:
#print(type(x))

In [5]:
#print(type(y))

In [6]:
%timeit np.arange(1,9)**4

1.43 µs ± 31.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Creating Numpy arrays

In [7]:
import numpy as np

In [8]:
x = [1,2,3]
#a  = np.array([1,2,3])
a  = np.array(x)
print(a)
print()
print(a.ndim)

[1 2 3]

1


# create a 3*3 numpy array of all True

In [9]:
np.ones((3,3),dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print()
print(arr2.ndim)
print()
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]

2

(2, 4)


In [11]:
arr3 = np.array([[[1,2,3,4],[5,6,7,8],[9,0,1,2]]])
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[1 2 3 4]
  [5 6 7 8]
  [9 0 1 2]]]
3
(1, 3, 4)


# How to you find ndimensional array

In [12]:
arrn = np.array([1,2,4,6],ndmin = 10)
print(arrn)
print(arrn.ndim)
print(arrn.shape)

[[[[[[[[[[1 2 4 6]]]]]]]]]]
10
(1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


In [13]:
arrn = np.array([1,5,8,9],ndmin = 16)
print(arrn)
print(arrn.ndim)
print(arrn.shape)

[[[[[[[[[[[[[[[[1 5 8 9]]]]]]]]]]]]]]]]
16
(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4)


In [14]:
arrn = np.array([1,2,4,6],ndmin = 1)
print(arrn)
print(arrn.ndim)

[1 2 4 6]
1


In [15]:
arrn2 = np.array([2,4,5,7],ndmin = 20)
print(arrn2)
print(arrn2.ndim)

[[[[[[[[[[[[[[[[[[[[2 4 5 7]]]]]]]]]]]]]]]]]]]]
20


# special type of array(fileld fith spevcific array)

# Create Numpy Arry using numpy function

# zero array

In [16]:
import numpy as np

In [17]:
arr_zero = np.zeros(4) 
arr_zeros1 = np.zeros((3,4),dtype = bool )
print(arr_zero)
print()
print(arr_zeros1)

[0. 0. 0. 0.]

[[False False False False]
 [False False False False]
 [False False False False]]


In [18]:
arr_zeros1 = np.zeros((3,3))
print(arr_zeros1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# One array

In [19]:
arr_one = np.ones(4)
print(arr_one)

[1. 1. 1. 1.]


In [20]:
arr_one = np.ones(5, dtype="i")
print(arr_one)
print()
arr2 = np.ones((3,2),dtype="i")
print(arr2)

[1 1 1 1 1]

[[1 1]
 [1 1]
 [1 1]]


In [21]:
arr_one = np.ones(3, dtype="i",order="F")
print(arr_one)

[1 1 1]


# Empty array1

In [22]:
arr_em=np.empty(4)
print(arr_em)

[4.24399158e-314 8.48798317e-314 1.27319747e-313 1.69759663e-313]


# range 

In [23]:
arr_rn = np.arange(4)
print(arr_rn)

[0 1 2 3]


# Dignoal elemengt

In [24]:
arr_dia = np.eye(3)
print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
arr_dia = np.eye(3,5)
print(arr_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [26]:
arr_dia = np.eye(4,5)
print(arr_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [27]:
arr_dia = np.eye(4,6, dtype="f")
print(arr_dia)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


# linespace function

In [28]:
arr_lin = np.linspace(0,10,num = 5)
print(arr_lin)

[ 0.   2.5  5.   7.5 10. ]


In [29]:
arr_lin = np.linspace(0,20,num = 5, dtype="i")
print(arr_lin)
print("data type :",arr_lin.dtype)
print()
print("find dim is ",arr_lin.dtype)

[ 0  5 10 15 20]
data type : int32

find dim is  int32


In [30]:
arr_lin = np.linspace(0,20,num = 4)
print(arr_lin)

[ 0.          6.66666667 13.33333333 20.        ]


In [31]:
arr_lin = np.linspace(0,20,num = 10,dtype="i")
print(arr_lin)
print(type(arr_lin ))
print(arr_lin.ndim )
print("dtpe",arr_lin.dtype)

[ 0  2  4  6  8 11 13 15 17 20]
<class 'numpy.ndarray'>
1
dtpe int32


In [32]:
arr_lin1 = np.linspace(0,20,num = 10)
print(arr_lin1)
print(type(arr_lin1))
print(arr_lin1.ndim )

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]
<class 'numpy.ndarray'>
1


# Creating Random Value Arrays

# Random

# Rand()

In [199]:
var = np.random.rand(5)
print(var)

[0.67645419 0.1151861  0.95798068 0.09171332 0.62979647]


In [207]:
var1 = np.random.rand(2,5)
print(var1)

[[0.73867458 0.64148666 0.25215639 0.47580894 0.26805668]
 [0.86826055 0.26688898 0.9730157  0.21355595 0.2977747 ]]


In [222]:
var1 = np.random.rand(4,3)
print(var1)

[[0.03111353 0.96101466 0.41902148]
 [0.37389271 0.50548305 0.04714255]
 [0.72915418 0.09262904 0.97565313]
 [0.41194036 0.78780219 0.9674221 ]]


# randn()

In [275]:
var2 = np.random.randn(5)
print(var2)

[-0.29032639 -0.17798034  0.76130187 -0.68198302 -1.56474201]


In [310]:
var3 = np.random.randn(5,6)
print(var3)

[[ 1.11550304e+00  7.87609210e-01  4.10103933e-01 -5.52505303e-01
  -4.87358100e-01 -2.44950241e+00]
 [-2.40496095e+00  6.92852443e-02  9.60991637e-01 -1.69735963e+00
  -1.23463909e+00 -1.09797525e+00]
 [ 6.04996056e-01 -2.17261882e-01 -6.45482112e-01 -1.35312192e+00
   4.11546886e-01  3.89096985e-01]
 [ 6.93277510e-04  5.74986514e-01  5.25301939e-01 -6.97250974e-02
   3.69911661e-01 -1.63965563e+00]
 [ 1.94782767e+00  6.84699950e-02  1.45830560e+00  7.18821532e-01
  -2.05590243e+00  6.64723426e-01]]


# randf

In [316]:
var4 = np.random.ranf((3,4))
print(var4)

[[0.04463989 0.07746665 0.72310759 0.51706375]
 [0.30193773 0.89065362 0.1465569  0.03666653]
 [0.20292182 0.44852489 0.14294611 0.82312588]]


In [39]:
var4 = np.random.ranf((4))
print(var4)

[0.12472216 0.88701296 0.72196299 0.66775559]


In [40]:
var4 = np.random.ranf(4)
print(var4)

[0.98573544 0.64474889 0.72037198 0.52012053]


# randint

In [328]:
var6 = np.random.randint(5,100,5)
print(var6)

[94 87 73 84 76]


# Data type in numpy array

In [42]:
var = np.array([1,4,6,7])
print("Data type :",var.dtype)

Data type : int32


In [43]:
var1 = np.array([1,4,6,7,8,12,13,45,67,89,90])
print("Data type :",var1.dtype)

Data type : int32


In [44]:
var1 = np.array([1.3,1.4,3.4,5.6])
print("Data type :",var1.dtype)

Data type : float64


In [45]:
var1 = np.array(["s","r","p","e"])
print("Data type :",var1.dtype)

Data type : <U1


In [46]:
var1 = np.array(["s","r","p","e",1,2,3,4,5])
print(var1)
print()
print("Data type :",var1.dtype)

['s' 'r' 'p' 'e' '1' '2' '3' '4' '5']

Data type : <U11


In [47]:
x = np.array([1,2,3,4])
print(x)
print("data type",x.dtype)

[1 2 3 4]
data type int32


In [48]:
x = np.array([1,2,3,4],dtype = np.int32)
print(x)
print()
print("data type",x.dtype)
y = np.float32(x)
print()
print(y)
print()
z = np.int32(y)
print(z)

[1 2 3 4]

data type int32

[1. 2. 3. 4.]

[1 2 3 4]


In [49]:
x1 = np.array([1,2,3,4],dtype = "f")
print(x1)
print("data type",x1.dtype)
y1 = np.int64(x1)
print(y1)
z1 = np.float64(y1)
print(z1)

[1. 2. 3. 4.]
data type float32
[1 2 3 4]
[1. 2. 3. 4.]


In [50]:
x1 = np.array([1,2,3,4],dtype = "i")
print(x1)
print("data type",x1.dtype)

[1 2 3 4]
data type int32


In [51]:
x2 = np.array([1,2,3,4])

new = np.float32(x2)
print(x2)
print("data type",x2.dtype)
print()
print(new)
print("data type",new.dtype)

[1 2 3 4]
data type int32

[1. 2. 3. 4.]
data type float32


In [52]:
x2 = np.array([1,2,3,4])

new = np.float32(x2)
new_one = np.int_(new)
print(x2)
print("data type",x2.dtype)
print()
print(new)
print("data type",new.dtype)
print(new_one)
print("data type",new_one.dtype)

[1 2 3 4]
data type int32

[1. 2. 3. 4.]
data type float32
[1 2 3 4]
data type int32


In [53]:
y = np.array([2,4,6,8])
print(y)
print("Data Type :",y.dtype)

[2 4 6 8]
Data Type : int32


In [54]:
y = np.array([2,4,6,8],dtype = np.int8)
print(y)
print("Data Type :",y.dtype)

[2 4 6 8]
Data Type : int8


In [55]:
y = np.array([2,4,6,8],dtype = np.float32)
print(y)
print("Data Type :",y.dtype)

[2. 4. 6. 8.]
Data Type : float32


In [56]:
y = np.array([2,4,6,8])
print(y)
print("Data Type :",y.dtype)
print()
new = np.float32(y)
print(new)
print(new.dtype)
print()
new_one = np.int32(y)
print(new_one)
print(new_one.dtype)
print()
new_one = np.float32(y)
print(new_one)
print(new_one.dtype)
print()
new_two = np.int_(new_one)
print(new_two)
print(new_two.dtype)

[2 4 6 8]
Data Type : int32

[2. 4. 6. 8.]
float32

[2 4 6 8]
int32

[2. 4. 6. 8.]
float32

[2 4 6 8]
int32


In [57]:
y1 = np.array([2,4,6,8])
print(y1)
new1 = y1.astype(float)
print(y1)
print(new1)

[2 4 6 8]
[2 4 6 8]
[2. 4. 6. 8.]


# shape & reshape in numpy array

# shape

In [331]:
var = np.array([[1,2],[2,3]])
print(var)
print(var.ndim)
print()
print(var.shape)

[[1 2]
 [2 3]]
2

(2, 2)


In [333]:
var = np.array([[1,2,3,4],[2,3,6,7]])
print(var)
print(var.ndim)
print()
print(var.shape)

[[1 2 3 4]
 [2 3 6 7]]
2

(2, 4)


In [335]:
var = np.array([1,2,3,4],ndmin = 5)
print(var)
print(var.ndim)
print()
print(var.shape)

[[[[[1 2 3 4]]]]]
5

(1, 1, 1, 1, 4)


In [336]:
var = np.array([1,2,3,4,7],ndmin = 7)
print(var)
print(var.ndim)
print()
print(var.shape)

[[[[[[[1 2 3 4 7]]]]]]]
7

(1, 1, 1, 1, 1, 1, 5)


# Reshape

In [337]:
var2 = np.array([1,2,34,5,6,7])
print(var2)
print(var2.ndim)
print(var2.shape)
print()
x = var2.reshape(3,2)
print(x)
print()
print(var2.ndim)
print(x.ndim)

[ 1  2 34  5  6  7]
1
(6,)

[[ 1  2]
 [34  5]
 [ 6  7]]

1
2


In [63]:
var4 = np.array([1,2,3,4,5,6,7,8,9])
print(var4)
print(var4.ndim)
print(var4.shape)
print()

var5 = var4.reshape(3,3)
print(var5)
print(var5.shape)
print(var5.ndim)

[1 2 3 4 5 6 7 8 9]
1
(9,)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


In [64]:
var6 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var6)
print(var6.ndim)
print(var6.shape)
print()

var7 = var6.reshape(2,3,2)
print(var7)
print(var7.shape)
print(var7.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
3


In [65]:
var6 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
print(var6)
print(var6.ndim)
print(var6.shape)
print()

var7 = var6.reshape(2,3,3)
print(var7)
print(var7.shape)
print(var7.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
1
(18,)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
(2, 3, 3)
3


In [66]:
var6 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
print(var6)
print(var6.ndim)
print(var6.shape)
print()

var7 = var6.reshape(6,3)
print(var7)
print(var7.shape)
print(var7.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
1
(18,)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
(6, 3)
2


In [67]:
var6 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
print(var6)
print(var6.ndim)
print(var6.shape)
print()

var7 = var6.reshape(2,3,3)
print(var7)
print(var7.shape)
print(var7.ndim)

print()


var8 = var7.reshape(-1)
print(var8)
print(var8.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
1
(18,)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
(2, 3, 3)
3

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
1


# numpy == arithmetic operation

In [68]:
var10 = np.array([1,2,34,5])
varadd = var10 + 3
print(varadd)

[ 4  5 37  8]


In [69]:
var11 = np.array([1,2,34,5])
var12 = np.array([1,5,6,9])
var13 = var11 + var12
print(var13)

[ 2  7 40 14]


In [70]:
var10 = np.array([1,2,34,5])
varadd = var10 - 3
print(varadd)

[-2 -1 31  2]


In [71]:
var11 = np.array([1,2,34,5])
var12 = np.array([1,5,6,9])
var13 = var11 - var12
print(var13)

[ 0 -3 28 -4]


In [72]:
var10 = np.array([1,2,34,5])
varadd = var10 / 3
print(varadd)

[ 0.33333333  0.66666667 11.33333333  1.66666667]


In [73]:
var11 = np.array([1,2,34,5])
var12 = np.array([1,5,6,9])
var13 = var11 / var12
print(var13)

[1.         0.4        5.66666667 0.55555556]


In [74]:
var10 = np.array([1,2,34,5])
varadd = var10 % 3
print(varadd)

[1 2 1 2]


In [75]:
var11 = np.array([1,2,34,5])
var12 = np.array([1,5,6,9])
var13 = var11 % var12
print(var13)

[0 2 4 5]


In [76]:
var10 = np.array([1,2,34,5])
varadd = var10 + 3
print(varadd)

[ 4  5 37  8]


In [77]:
var11 = np.array([1,2,34,5])
var12 = np.array([1,5,6,9])
var13 = np.add(var11,var12)
print(var13)

[ 2  7 40 14]


In [78]:
var10 = np.array([1,2,34,5])
varadd = np.reciprocal(var10)
print(varadd)

[1 0 0 0]


# 2d array

In [79]:
var14 = np.array([[1,2,34,5],[6,8,9,3]])
var15 = np.array([[1,2,34,5],[6,8,9,3]])
varadd = var14 + var15 
print(varadd)

[[ 2  4 68 10]
 [12 16 18  6]]


In [80]:
var14 = np.array([[1,2,34,5],[6,8,9,3]])
var15 = np.array([[1,2,34,5],[6,8,9,3]])

print()

print(var14)
print()
print(var15)

print()

varadd = var14 + var15 
print(varadd)


[[ 1  2 34  5]
 [ 6  8  9  3]]

[[ 1  2 34  5]
 [ 6  8  9  3]]

[[ 2  4 68 10]
 [12 16 18  6]]


In [343]:
var16 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,20,23])
print("min: ", np.min(var16), np.argmin(var16))
print()
print("max :", np.max(var16),np.argmax(var16))
print()
print("sqt : ", np.sqrt(var16))

min:  1 0

max : 23 19

sqt :  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.47213595 4.79583152]


In [82]:
var17 = np.array([[1,2,34,5],[6,8,9,3]])
print(np.max(var17,axis = 1))
print(np.max(var17,axis = 0))

[34  9]
[ 6  8 34  5]


In [342]:
var18 = np.array([1,2,3,5,9])
print(np.sin(var18))
print()
print(np.cos(var18))
print()
print(np.cumsum(var18))

[ 0.84147098  0.90929743  0.14112001 -0.95892427  0.41211849]

[ 0.54030231 -0.41614684 -0.9899925   0.28366219 -0.91113026]

[ 1  3  6 11 20]


In [84]:
import pandas as np

# Numpy Array iterating

In [85]:
var = np.array([3,6,7,9,3])
print(var)
print(var.ndim)
print(var.shape)

<IntegerArray>
[3, 6, 7, 9, 3]
Length: 5, dtype: Int64
1
(5,)


In [86]:
for i in var:
    print(i)

3
6
7
9
3


In [87]:
var2 = np.array([[4,6,8,9],[2,5,3,4]])
print(var2)
print(var2.shape)
print(var2.ndim)
print()

for j in var2:
    print(i)
print()    
    
for K in var2:
    for l in K:
        print(l)
    

<PandasArray>
[[4, 6, 8, 9], [2, 5, 3, 4]]
Length: 2, dtype: object
(2,)
1

3
3

4
6
8
9
2
5
3
4


In [88]:
var3 = np.array([[[2,5,7,8],[2,7,4,7]]])
print(var3)
print(var3.ndim)
print(var3.shape)
print()

for i in var3:
    print(i)
print()

for j in var3:
    for K in j:
        for l in K:
            print(l)

<PandasArray>
[[[2, 5, 7, 8], [2, 7, 4, 7]]]
Length: 1, dtype: object
1
(1,)

[[2, 5, 7, 8], [2, 7, 4, 7]]

2
5
7
8
2
7
4
7


In [89]:
var4 = np.array([[[6,7,4,9],[2,7,4,7]]])
print(var4)
print(var4.ndim)
print(var4.shape)
print()

for i in var4:
    print(i)
print()

for j in var4:
    for K in j:
        for l in K:
            print(l)

<PandasArray>
[[[6, 7, 4, 9], [2, 7, 4, 7]]]
Length: 1, dtype: object
1
(1,)

[[6, 7, 4, 9], [2, 7, 4, 7]]

6
7
4
9
2
7
4
7


In [90]:
import numpy as np

In [91]:
var5 = np.array([[[6,7,4,4],[2,7,47,4]]])
print(var5)
print(var5.ndim)
print(var5.shape)
print()

for i in np.nditer(var5):
    print(i)

[[[ 6  7  4  4]
  [ 2  7 47  4]]]
3
(1, 2, 4)

6
7
4
4
2
7
47
4


In [92]:
var5 = np.array([[[6,7,4,4],[2,7,47,4]]])
print(var5)
print(var5.ndim)
print(var5.shape)
print()

for i in np.nditer(var5,flags = ["buffered"],op_dtypes=["S"]):
    print(i)

[[[ 6  7  4  4]
  [ 2  7 47  4]]]
3
(1, 2, 4)

b'6'
b'7'
b'4'
b'4'
b'2'
b'7'
b'47'
b'4'


In [93]:
var5 = np.array([[[6,7,4,4],[2,7,47,4]]])
print(var5)
print(var5.ndim)
print(var5.shape)
print()

for i in np.nditer(var5):
    print(i)
print()    
    
    
for i,d in np.ndenumerate(var5):
    print(i,d)

[[[ 6  7  4  4]
  [ 2  7 47  4]]]
3
(1, 2, 4)

6
7
4
4
2
7
47
4

(0, 0, 0) 6
(0, 0, 1) 7
(0, 0, 2) 4
(0, 0, 3) 4
(0, 1, 0) 2
(0, 1, 1) 7
(0, 1, 2) 47
(0, 1, 3) 4


# THe difference between Copy Vs View 

# copy vs view in numpy array

In [94]:
import numpy as np

In [95]:
var45 = np.array([4,6,9,6])
print()
co = var45.copy()

var45[2] = 45

print(var45)
print("copt",co)


[ 4  6 45  6]
copt [4 6 9 6]


In [96]:
var46 = np.array([4,8,1,6])
print()
vi = var46.view()
var46[2] = 79
print(var46)
print(vi)


[ 4  8 79  6]
[ 4  8 79  6]


# join Array

In [97]:
import numpy as np

In [98]:
var50 = np.array([2,7,4,6])
var51 = np.array([8,9,7,5])

In [99]:
var52 = np.concatenate((var50,var51))

In [100]:
print(var52)

[2 7 4 6 8 9 7 5]


In [101]:
var53 = np.array([[2,7],[4,6]])
var54 = np.array([[8,9],[7,5]])

In [102]:
var55 = np.concatenate((var53,var54))

In [103]:
print(var55)

[[2 7]
 [4 6]
 [8 9]
 [7 5]]


In [104]:
var56 = np.concatenate((var53,var54),axis = 0)

In [105]:
print(var56)

[[2 7]
 [4 6]
 [8 9]
 [7 5]]


In [106]:
var57 = np.concatenate((var53,var54),axis = 1)

In [107]:
print(var57)

[[2 7 8 9]
 [4 6 7 5]]


In [108]:
var58 = np.array([9,7,4,6])
var59 = np.array([5,9,7,3])

In [109]:
var60 = np.stack((var58,var59),axis = 1)

In [110]:
print(var60)

[[9 5]
 [7 9]
 [4 7]
 [6 3]]


In [111]:
var61 = np.stack((var58,var59),axis = 0)

In [112]:
print(var61)

[[9 7 4 6]
 [5 9 7 3]]


In [113]:
var62 = np.hstack((var58,var59))

In [114]:
print(var62)

[9 7 4 6 5 9 7 3]


In [115]:
var63 = np.vstack((var58,var59))

In [116]:
print(var63)

[[9 7 4 6]
 [5 9 7 3]]


In [117]:
var64 = np.dstack((var58,var59))

In [118]:
print(var64)

[[[9 5]
  [7 9]
  [4 7]
  [6 3]]]


# split array

In [119]:
var65 = np.array([7,4,8,2,7,9,4,7])
var66 = np.array_split(var65,4)
print()
print(var65)
print()
print(var66)
print(type(var66))
print(var66[2])


[7 4 8 2 7 9 4 7]

[array([7, 4]), array([8, 2]), array([7, 9]), array([4, 7])]
<class 'list'>
[7 9]


In [120]:
var65 = np.array([[7,4],[8,2],[7,9],[4,7]])
var66 = np.array_split(var65,4)
print()
print(var65)
print()
print(var66)
print(type(var66))
print(var66[2])


[[7 4]
 [8 2]
 [7 9]
 [4 7]]

[array([[7, 4]]), array([[8, 2]]), array([[7, 9]]), array([[4, 7]])]
<class 'list'>
[[7 9]]


In [121]:
var65 = np.array([[7,4],[8,2],[7,9],[4,7]])
var66 = np.array_split(var65,4)
var67 = np.array_split(var65,4, axis = 0)
print()
print(var65)
print()
print(var66)
print(type(var66))
print(var66[2])
print()
print(var67)


[[7 4]
 [8 2]
 [7 9]
 [4 7]]

[array([[7, 4]]), array([[8, 2]]), array([[7, 9]]), array([[4, 7]])]
<class 'list'>
[[7 9]]

[array([[7, 4]]), array([[8, 2]]), array([[7, 9]]), array([[4, 7]])]


In [122]:
var65 = np.array([[7,4],[8,2],[7,9],[4,7]])
var66 = np.array_split(var65,4)
var67 = np.array_split(var65,4, axis = 1)
print()
print(var65)
print()
print(var66)
print(type(var66))
print(var66[2])
print()
print(var67)


[[7 4]
 [8 2]
 [7 9]
 [4 7]]

[array([[7, 4]]), array([[8, 2]]), array([[7, 9]]), array([[4, 7]])]
<class 'list'>
[[7 9]]

[array([[7],
       [8],
       [7],
       [4]]), array([[4],
       [2],
       [9],
       [7]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]


# search array

In [123]:
var68 = np.array([6,8,9,3,9,4,9,5,3,9,3,9,7])
var69 = np.where(var68 == 9)
print()
print(var69)


(array([ 2,  4,  6,  9, 11], dtype=int64),)


In [124]:
var68 = np.array([6,8,9,3,9,4,9,5,3,9,3,9,7])
var69 = np.where((var68%2) == 0)
print()
print(var69)


(array([0, 1, 5], dtype=int64),)


# search sort11

In [125]:
var68 = np.array([1,2,3,4,6,7,8,9])
var69 = np.searchsorted(var68,5)
print()
print(var69)


4


In [126]:
var68 = np.array([1,2,3,4,6,7,8,9])
var69 = np.searchsorted(var68,5,side = "right")
print()
print(var69)


4


In [127]:
var68 = np.array([1,2,3,4,6,7,8,9])
var69 = np.searchsorted(var68,[5,6,7],side = "right")
print()
print(var69)


[4 5 6]


# sort

In [128]:
var70 = np.array([6,8,9,3,1,4,0,7])
var71 = np.sort(var70)
print()
print(var71)


[0 1 3 4 6 7 8 9]


In [129]:
var70 = np.array([[6,8,9],[3,1,4],[0,7,2]])
var71 = np.sort(var70)
print()
print(var71)


[[6 8 9]
 [1 3 4]
 [0 2 7]]


# filter array

In [130]:
var72 = np.array(["q","y","u","a"])
f = [True,False,False,True]
var73 = var72[f]
print(var73)

['q' 'a']


# Numpy Array function

# shuffle

In [131]:
var74 = np.array([1,2,3,4,6,7,8,9])
print(var74)
print()
np.random.shuffle(var74)
print(var74)

[1 2 3 4 6 7 8 9]

[2 1 3 9 7 4 8 6]


# unique

In [132]:
var76 = np.array([6,8,9,3,9,4,9,5,3,9,3,9,7])
print(var76)
print()
var77 = np.unique(var76)
print(var77)

[6 8 9 3 9 4 9 5 3 9 3 9 7]

[3 4 5 6 7 8 9]


In [133]:
var76 = np.array([6,8,9,3,9,4,9,5,3,9,3,9,7])
print(var76)
print()
var77 = np.unique(var76,return_index= True)
print(var77)

[6 8 9 3 9 4 9 5 3 9 3 9 7]

(array([3, 4, 5, 6, 7, 8, 9]), array([ 3,  5,  7,  0, 12,  1,  2], dtype=int64))


In [134]:
var76 = np.array([6,8,9,3,9,4,9,5,3,9,3,9,7])
print(var76)
print()
var77 = np.unique(var76,return_index= True,return_counts=True)
print(var77)

[6 8 9 3 9 4 9 5 3 9 3 9 7]

(array([3, 4, 5, 6, 7, 8, 9]), array([ 3,  5,  7,  0, 12,  1,  2], dtype=int64), array([3, 1, 1, 1, 1, 1, 5], dtype=int64))


# Resize

In [135]:
var78 = np.array([6,8,9,3,9,4,9,5,3,9,3,7])
print(var78)
print()
var79 = np.resize(var78,(3,4))
print(var79)

[6 8 9 3 9 4 9 5 3 9 3 7]

[[6 8 9 3]
 [9 4 9 5]
 [3 9 3 7]]


In [136]:
var78 = np.array([6,8,9,3,9,4,9,5,3,9,3,7])
print(var78)
print()
var79 = np.resize(var78,(4,3))
print(var79)

[6 8 9 3 9 4 9 5 3 9 3 7]

[[6 8 9]
 [3 9 4]
 [9 5 3]
 [9 3 7]]


# Flatten and Reval

In [137]:
var78 = np.array([6,8,9,3,9,4,9,5,3,9,3,7])
print(var78)
print()
var79 = np.resize(var78,(4,3))
print(var79)

[6 8 9 3 9 4 9 5 3 9 3 7]

[[6 8 9]
 [3 9 4]
 [9 5 3]
 [9 3 7]]


In [138]:
print(var78.flatten())

[6 8 9 3 9 4 9 5 3 9 3 7]


In [139]:
print(var78.flatten(order = "F"))

[6 8 9 3 9 4 9 5 3 9 3 7]


In [140]:
print("reval", np.ravel(var78,order = "K"))

reval [6 8 9 3 9 4 9 5 3 9 3 7]


# Insert and delete funcation

In [141]:
import numpy as np

In [142]:
var80 = np.array([4,5,6,7,8])
print(var80)

[4 5 6 7 8]


In [143]:
var81 = np.insert(var80,3,70)
print(var81)

[ 4  5  6 70  7  8]


In [144]:
var81 = np.insert(var80,(2,3),9)
print(var81)

[4 5 9 6 9 7 8]


In [145]:
var82 = np.array([[1,2,3],[1,2,3]])
print(var82)

[[1 2 3]
 [1 2 3]]


In [146]:
var83 = np.insert(var82, 2, 7, axis = 0)
print(var82)

[[1 2 3]
 [1 2 3]]


In [147]:
var83 = np.insert(var82, 2, 7, axis = 1)
print(var82)

[[1 2 3]
 [1 2 3]]


In [148]:
var84 = np.append(var82,6.6)
print(var84)

[1.  2.  3.  1.  2.  3.  6.6]


In [149]:
var85 =  np.append(var82,[[67,78,98]],axis = 0)
print(var85)

[[ 1  2  3]
 [ 1  2  3]
 [67 78 98]]


# Delete

In [150]:
var86 = np.array([6,8,9,4])
print(var86)

[6 8 9 4]


In [151]:
var87 = np.delete(var86,2)
print(var87)

[6 8 4]


# Numpy Matrix

In [152]:
import numpy as np


In [153]:
var88 = np.matrix([[1,2,4],[4,5,6]])
print(var88)
print(type(var88))

[[1 2 4]
 [4 5 6]]
<class 'numpy.matrix'>


In [154]:
var89 = np.array([[1,2,4],[4,5,6]])
print(var89)
print(type(var89))

[[1 2 4]
 [4 5 6]]
<class 'numpy.ndarray'>


In [155]:
var90 = np.matrix([[1,2,4],[4,5,6]])
var91 = np.matrix([[1,2,4],[4,5,6]])
print(var90)
print(type(var90))
print()
print(var90 + var91)


[[1 2 4]
 [4 5 6]]
<class 'numpy.matrix'>

[[ 2  4  8]
 [ 8 10 12]]


In [156]:
var90 = np.matrix([[1,2],[4,5]])
var91 = np.matrix([[1,2],[4,5]])
print(var90)
print()
print(var90*var91)
print()
print(var90.dot(var91))

[[1 2]
 [4 5]]

[[ 9 12]
 [24 33]]

[[ 9 12]
 [24 33]]


# Matrix function

# Transpose

# Transpose

In [157]:
var92 = np.matrix([[1,2,7],[4,5,9]])
print(var92)
print()
print(np.transpose(var92))
print()
print(var92.T)

[[1 2 7]
 [4 5 9]]

[[1 4]
 [2 5]
 [7 9]]

[[1 4]
 [2 5]
 [7 9]]


# Swapaxes

In [158]:
var93 = np.matrix([[1,2,7],[4,5,9]])
print(var93)
print()
print(np.swapaxes(var93,0,1))

[[1 2 7]
 [4 5 9]]

[[1 4]
 [2 5]
 [7 9]]


# inverse

In [159]:
var94 = np.matrix([[1,2],[4,5]])
print(var94)
print()
print(np.linalg.inv(var94))

[[1 2]
 [4 5]]

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


# power of matrix

In [160]:
var95 = np.matrix([[7,8],[9,5]])
print(var95)
print()
print(np.linalg.matrix_power(var95,4))
print()
print(np.linalg.matrix_power(var95,0))
print()
print(np.linalg.matrix_power(var95,-2))

[[7 8]
 [9 5]]

[[25009 20928]
 [23544 19777]]

[[1 0]
 [0 1]]

[[ 0.07085464 -0.07012418]
 [-0.0788897   0.08838568]]


# Determinate of matrix

In [161]:
var96 = np.matrix([[8,5],[9,2]])
print(var96)
print()
print(np.linalg.det(var96))

[[8 5]
 [9 2]]

-29.000000000000004


In [162]:
var97 = np.matrix([[8,5,3],[9,2,7],[1,6,4]])
print(var97)
print()
print(np.linalg.det(var97))

[[8 5 3]
 [9 2 7]
 [1 6 4]]

-261.00000000000006


In [163]:
var98 = np.matrix([[8,5,3],[9,2,7],[8,5,3]])
print(var98)
print()
print(np.linalg.det(var98))

[[8 5 3]
 [9 2 7]
 [8 5 3]]

0.0


# Slicing and indexing

In [164]:
import numpy as np

In [165]:
var98 = np.array([[8,5,3],[9,2,7],[8,5,3]])
print(var98)
print()

[[8 5 3]
 [9 2 7]
 [8 5 3]]



In [166]:
var98[2:3,1:2]

array([[5]])

In [167]:
var98[1:3,1:3]

array([[2, 7],
       [5, 3]])

In [168]:
var98[:,2:3]

array([[3],
       [7],
       [3]])

In [169]:
np.random.seed(111)
varr99 = np.random.randint(1,1500,30).reshape(6,5)
varr99

array([[ 877,  725,   87, 1300,  682],
       [1347,  119,  809,  968,  954],
       [1032, 1293, 1291, 1474,  729],
       [1309, 1295,  419, 1046,  713],
       [  38,  973,  269,  686,  335],
       [ 345,  526,  563,  748, 1495]])

In [170]:
varr99[4:5,3:4]

array([[686]])

In [171]:
varr99[::-1]

array([[ 345,  526,  563,  748, 1495],
       [  38,  973,  269,  686,  335],
       [1309, 1295,  419, 1046,  713],
       [1032, 1293, 1291, 1474,  729],
       [1347,  119,  809,  968,  954],
       [ 877,  725,   87, 1300,  682]])

In [172]:
varr99[:,::-1]

array([[ 682, 1300,   87,  725,  877],
       [ 954,  968,  809,  119, 1347],
       [ 729, 1474, 1291, 1293, 1032],
       [ 713, 1046,  419, 1295, 1309],
       [ 335,  686,  269,  973,   38],
       [1495,  748,  563,  526,  345]])

In [173]:
varr100 = varr99.reshape(-1)
varr100

array([ 877,  725,   87, 1300,  682, 1347,  119,  809,  968,  954, 1032,
       1293, 1291, 1474,  729, 1309, 1295,  419, 1046,  713,   38,  973,
        269,  686,  335,  345,  526,  563,  748, 1495])

In [174]:
varr100[::-1].reshape(6,5)

array([[1495,  748,  563,  526,  345],
       [ 335,  686,  269,  973,   38],
       [ 713, 1046,  419, 1295, 1309],
       [ 729, 1474, 1291, 1293, 1032],
       [ 954,  968,  809,  119, 1347],
       [ 682, 1300,   87,  725,  877]])

In [175]:
varr99

array([[ 877,  725,   87, 1300,  682],
       [1347,  119,  809,  968,  954],
       [1032, 1293, 1291, 1474,  729],
       [1309, 1295,  419, 1046,  713],
       [  38,  973,  269,  686,  335],
       [ 345,  526,  563,  748, 1495]])

In [176]:
varr99[::-3]

array([[ 345,  526,  563,  748, 1495],
       [1032, 1293, 1291, 1474,  729]])

In [177]:
varr99[5,4]

1495

In [178]:
varr99[4,3]

686

In [179]:
varr99[4:6,3:5]

array([[ 686,  335],
       [ 748, 1495]])

In [180]:
varr99[2,2]

1291

In [181]:
varr100[::-4]

array([1495,  345,  973,  419, 1474,  954, 1347,  725])