In [56]:
import numpy as np

# Create an array of 10 zeros

In [2]:
varr1 = np.zeros(10)
print(varr1)
print()

varr2 = np.zeros(10,dtype = "i")
print(varr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[0 0 0 0 0 0 0 0 0 0]


# create an array 10 ones

In [3]:
varr3 = np.ones(10)
print(varr3)
print()
varr4 = np.ones(10,dtype = "i")
print(varr4)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[1 1 1 1 1 1 1 1 1 1]


# create an array 10 fives

In [4]:
varr5 = np.ones(10,dtype = "i")
print(varr5)
print()
varr6 = 5*varr5
print(varr6)

[1 1 1 1 1 1 1 1 1 1]

[5 5 5 5 5 5 5 5 5 5]


# create an array 10 seven

In [5]:
varr6 = np.ones(10)
print(varr6)
print()
varr7 = 7*varr6
print(varr7)
print()
varr8 = np.int64(varr7)
print(varr8)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]

[7 7 7 7 7 7 7 7 7 7]


# create an integer from 10 and 50

In [6]:
varr9 = np.arange(10,50)
print(varr9)
print()
print(varr9.shape)
print()
varr15 = varr9.reshape(8,5)
print(varr15)
print()
varr16 = varr15.reshape(5,8)
print(varr16)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

(40,)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]

[[10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25]
 [26 27 28 29 30 31 32 33]
 [34 35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48 49]]


# create 3 * 3 matrix with value ranging 0 to 8

In [3]:
varr10 = np.arange(0,9)
print(varr10)
print(varr10.shape)
print()
varr11 = varr10.reshape(3,3)
print(varr11)

[0 1 2 3 4 5 6 7 8]
(9,)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# create an even integer from 10 and 50

In [8]:
varr12 = np.arange(10,50,2)
print(varr12)
print(varr12.shape)
print()
varr13 = varr12.reshape(4,5)
print(varr13)
print(varr13.shape)
print(varr13.ndim)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
(20,)

[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]
(4, 5)
2


# create an  integer from 10 and 50

In [9]:
varr12 = np.arange(10,80,5)
print(varr12)
print(varr12.shape)
print()
varr13 = varr12.reshape(7,2)
print(varr13)
print(varr13.shape)
print(varr13.ndim)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75]
(14,)

[[10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]
 [60 65]
 [70 75]]
(7, 2)
2


# create 3*3 identity matrix

In [4]:
varr14 = np.eye(3,3)
print(varr14)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# use numpy to generate a random number between 0 and 1

In [58]:
varr15 = np.random.rand()
print(varr15)

0.35914630675101966


# use numpy to generate an array 25 random numbers sampled from  a standard normal distribution

In [66]:
varr16 = np.random.randn(25)
print(varr16)
print()

[-0.30171923  1.27057728 -0.59830899  1.47392358 -1.01725119  1.16192389
  1.17419614 -0.40341867  1.40918393 -0.97951184  0.68965652 -0.00860573
  0.94541551 -1.05002269  0.99805547 -0.69772918  1.02447763  1.11515712
  0.47204802 -3.44864385  1.00471851 -0.6147133  -0.41456137  0.24369852
  1.0628985 ]



In [67]:
varr17 = np.random.standard_normal(25)
print(varr17)

[ 0.16949567 -0.60123779 -0.4233718  -0.00626139 -0.53028725 -0.05718658
 -1.21276242  0.29780691 -0.29778367  0.51341761 -0.28041075 -0.51914402
  1.42087851  1.04376363  0.11698567  1.75547427 -1.10449897  1.26003858
 -0.50562012 -2.2787802   1.44626606 -0.0405734   0.23570707  0.19008498
 -0.10190831]


# create an 20 linear space points between 0 and 1

In [75]:
varr18 = np.linspace(0,1, num = 20)
print(varr18)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


# create the following matrix

In [77]:
import numpy as np

A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
C = A + B      # element wise addition
print(C)

[[11  1]
 [ 8  0]]


# Numpy indexing and selection

In [79]:
varr20 = np.arange(1,26)
print(varr20)
print(varr20.shape)
print()
varr21 = varr20.reshape(5,5)
print(varr21)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
(25,)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [17]:
varr21[::-1]

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [18]:
varr21[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [19]:
varr21[3,4]

20

In [20]:
varr21[0:3,1]

array([ 2,  7, 12])

In [21]:
varr21[0:3,1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [22]:
varr22 = varr21[0:3,1].reshape(3,1)
print(varr22)

[[ 2]
 [ 7]
 [12]]


In [23]:
varr21[4,:]

array([21, 22, 23, 24, 25])

In [24]:
varr21[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
varr21[::-1,:]

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [26]:
varr21[:,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16],
       [25, 24, 23, 22, 21]])

In [27]:
varr21[:,::4]

array([[ 1,  5],
       [ 6, 10],
       [11, 15],
       [16, 20],
       [21, 25]])

In [28]:
varr21[::4,:]

array([[ 1,  2,  3,  4,  5],
       [21, 22, 23, 24, 25]])

# get the sum of all values 

In [80]:
varr23 = varr21.sum()
varr23

325

# Get Standard deviation of all values

In [81]:
varr24 = varr21.std()
varr24

7.211102550927978

# get the sum of all values columns wise and row wise

In [82]:
varr25 = varr21.sum(axis = 1)
varr25

array([ 15,  40,  65,  90, 115])

In [83]:
varr26 = varr21.sum(axis = 0)
varr26

array([55, 60, 65, 70, 75])

# create a 1D array of number from 0 to 9

In [85]:
varr28 = np.arange(9)
print(varr28)
print(varr28.ndim)

[0 1 2 3 4 5 6 7 8]
1


# create 3*3 numpy array of all true's

In [34]:
varr29 = np.ones((3,3),dtype = bool)
print(varr29)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [86]:
varr29 = np.ones((3,3),dtype = "f")
print(varr29)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# extract all odd number from arr

In [3]:
import numpy as np

In [29]:
varr83 = np.arange(50)
print(varr83)
print()
varr84 = varr83%2 != 0
print(varr84)
print()
varr85 = varr83[varr83%2 != 0]
print(varr85)
print(varr85.shape)
print()
varr86 = varr85.reshape(5,5)
print(varr86)
print()
print(varr86.ndim)
print()
print(varr86.shape)
print()
print(varr86.dtype)
print()
varr87 = np.float64(varr86)
print(varr87)
print()
varr88 = np.int_(varr87)
print(varr88)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]

[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True]

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
(25,)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]

2

(5, 5)

int32

[[ 1.  3.  5.  7.  9.]
 [11. 13. 15. 17. 19.]
 [21. 23. 25. 27. 29.]
 [31. 33. 35. 37. 39.]
 [41. 43. 45. 47. 49.]]

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]


In [36]:
varr30 = np.arange(20)
print(varr30)
varr31 = varr30%2 == 1
varr31 = varr30[varr30%2 == 1]
varr31

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# extract all even number from arr

In [113]:
varr30 = np.arange(20)
print(varr30)
print()
varr31 = varr30%2 == 0
print(varr31)
print()
varr31 = varr30[varr30%2 == 0]
print(varr31)
print()
varr82 = varr31.dtype
print(varr82)
print()
varr83 = np.float64(varr30)
print(varr83)
print()
varr84 = np.int_(varr83)
print(varr83)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False]

[ 0  2  4  6  8 10 12 14 16 18]

int32

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


In [121]:
varr32 = np.arange(20)
print(varr32)
print(varr32.shape)
print()
varr33 = varr32.reshape(4,5)
print(varr33)
print()
varr34 = varr33%2 == 1
varr34 = varr33[varr33%2 == 1]
print(varr34)
print(varr34.shape)
print()
varr35 = varr34.reshape(2,5)
print(varr35)
print()
varr86 = np.ravel(varr35)
print(varr86)
print()
varr87 = varr35.flatten()
print(varr87)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[ 1  3  5  7  9 11 13 15 17 19]
(10,)

[[ 1  3  5  7  9]
 [11 13 15 17 19]]

[ 1  3  5  7  9 11 13 15 17 19]

[ 1  3  5  7  9 11 13 15 17 19]


In [122]:
varr32 = np.arange(20)
print(varr32)
print(varr32.shape)
print()
varr33 = varr32.reshape(4,5)
print(varr33)
print()
varr34 = varr33%2 == 0
varr34 = varr33[varr33%2 == 0]
print(varr34)
print(varr34.shape)
print()
varr35 = varr34.reshape(2,5)
print(varr35)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[ 0  2  4  6  8 10 12 14 16 18]
(10,)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


# replace all odd number in arr with -1

In [123]:
varr36 = np.arange(10)
print(varr36)
varr37 = varr36%2==1
varr37
varr38 = varr36[varr37]
print(varr38)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [124]:
varr36[varr36%2 == 1] = -1
varr36

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# replace all even number in arr with -1

In [2]:
import numpy as np

In [11]:
varr100 = np.arange(20,80)
print(varr100)
print()
varr101 = varr100%2 == 0
print(varr101)
print()
varr102 = varr100[varr100%2 == 0]
print(varr102)
print()
varr100[varr100%2 == 0]=-1
print(varr100)
print()
print(varr100.dtype)
print(varr100.shape)
print()
print(varr100.reshape(12,5))
print()
print()
varr103 = varr100.reshape(-1)
print("reshape",varr103.reshape(-1))
print()
varr104 = varr100.flatten()
print("Faltten", varr104)
print()
varr105 = np.ravel(varr100)
print("ravel", varr105)


[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79]

[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True False  True False]

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78]

[-1 21 -1 23 -1 25 -1 27 -1 29 -1 31 -1 33 -1 35 -1 37 -1 39 -1 41 -1 43
 -1 45 -1 47 -1 49 -1 51 -1 53 -1 55 -1 57 -1 59 -1 61 -1 63 -1 65 -1 67
 -1 69 -1 71 -1 73 -1 75 -1 77 -1 79]

int32
(60,)

[[-1 21 -1 23 -1]
 [25 -1 27 -1 29]
 [-1 31 -1 33 -1]
 [35 -1 37 -1 39]
 [-1 41 -1 43 -1]
 [45 -1 47 -1 49]
 [-1 51 -1 53 -1]
 [55 -1 57 -1 59]
 [-1 61 -1 6

In [9]:
varr38 = np.arange(10,60)
print(varr38)
varr38%2 == 0
varr38[varr38%2 == 0]
print()
varr38[varr38%2 == 0] = -1
print(varr38)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59]

[-1 11 -1 13 -1 15 -1 17 -1 19 -1 21 -1 23 -1 25 -1 27 -1 29 -1 31 -1 33
 -1 35 -1 37 -1 39 -1 41 -1 43 -1 45 -1 47 -1 49 -1 51 -1 53 -1 55 -1 57
 -1 59]


# replace all even number in arr with -1 without chganging arr

In [43]:
np.where(varr38%2 == 0,-1,varr38)

array([-1, 11, -1, 13, -1, 15, -1, 17, -1, 19, -1, 21, -1, 23, -1, 25, -1,
       27, -1, 29, -1, 31, -1, 33, -1, 35, -1, 37, -1, 39, -1, 41, -1, 43,
       -1, 45, -1, 47, -1, 49, -1, 51, -1, 53, -1, 55, -1, 57, -1, 59])

# convert 1 D to 2D array  with 2 row

In [44]:
varr39 = np.arange(8)
print(varr39)
print(varr39.shape)
print()
varr40 = varr39.reshape(2,4)
print(varr40)
print(varr40.ndim)
print()

[0 1 2 3 4 5 6 7]
(8,)

[[0 1 2 3]
 [4 5 6 7]]
2



# create 2D array of size 3*3 but all the element should be between 0 and 1

In [14]:
varr104 = np.random.rand(9)
print(varr104)
print()
varr105 = varr104.reshape(3,3)
print(varr105)
print()
varr106 = varr105.ndim
print(varr106)

[0.0686773  0.06082606 0.22152121 0.85985698 0.36456077 0.01456715
 0.61972209 0.82312269 0.56487656]

[[0.0686773  0.06082606 0.22152121]
 [0.85985698 0.36456077 0.01456715]
 [0.61972209 0.82312269 0.56487656]]

2


# How to stack arrays a and b vertically

In [16]:
varr41 = np.arange(20).reshape(4,5)
varr42 = np.arange(1,21).reshape(4,5)
print()
print(varr41)
print()
print(varr42)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
varr43 = np.vstack((varr41,varr42))
print(varr43)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [20]:
varr46 = np.concatenate((varr41,varr42),axis = 0)
print(varr46)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# How to stack arrays a and b horizontally

In [18]:
varr44 = np.hstack((varr41,varr42))
print(varr44)

[[ 0  1  2  3  4  1  2  3  4  5]
 [ 5  6  7  8  9  6  7  8  9 10]
 [10 11 12 13 14 11 12 13 14 15]
 [15 16 17 18 19 16 17 18 19 20]]


In [49]:
varr45 = np.concatenate((varr41,varr42),axis = 1)
print(varr45)

[[ 0  1  2  3  4  1  2  3  4  5]
 [ 5  6  7  8  9  6  7  8  9 10]
 [10 11 12 13 14 11 12 13 14 15]
 [15 16 17 18 19 16 17 18 19 20]]


# How to get the common items between two python numpy arrays?¶

In [22]:
varr46 = np.arange(10).reshape(2,5)
varr47 = np.arange(1,11).reshape(2,5)
print()
print(varr46)
print()
print(varr47)


[[0 1 2 3 4]
 [5 6 7 8 9]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [24]:
varr48 = np.intersect1d(varr46,varr47)
print(varr48)
print(varr48.shape)
print()
varr49 = varr48.reshape(3,3)
print(varr49)

[1 2 3 4 5 6 7 8 9]
(9,)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# from array c remove  all item present in array d

In [25]:
varr50 = np.array([1,2,3,4,5])
varr51 = np.array([6,3,8,4,9])

In [53]:
varr52 = np.setdiff1d(varr50,varr51)
varr52

array([1, 2, 5])

# get position where element of two array match

In [27]:
varr53 = np.arange(15)
varr54 = np.arange(15)
print(varr53)
print(varr54)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [55]:
varr55 = np.where(varr53 == varr54)
print(varr55)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int64),)


In [28]:
varr56 = np.array([1,2,3,2,3,4,3,4,5,6])
varr57 = np.array([7,2,10,2,7,4,9,4,9,9])
print(varr56)
print(varr57)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  9]


In [29]:
varr58 = np.where(varr56 == varr57)
print(varr58)

(array([1, 3, 5, 7], dtype=int64),)


# Get all element between 5 and 10 from array

In [30]:
varr59 = np.arange(15)
print(varr59)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [31]:
(varr59>=5)&(varr59<=10)

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True, False, False, False, False])

In [32]:
varr59[(varr59>=5)&(varr59<=10)]

array([ 5,  6,  7,  8,  9, 10])

# method 2

In [33]:
np.where(np.logical_and((varr59>=5),(varr59<=10)))

(array([ 5,  6,  7,  8,  9, 10], dtype=int64),)

# method 2

In [61]:
varr60 = np.arange(15)
varr60

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [62]:
varr61 = np.where((varr60>=5)&(varr60<=10))
varr61

(array([ 5,  6,  7,  8,  9, 10], dtype=int64),)

# How can you reverse a NumPy array?

In [34]:
varr62 = np.arange(18).reshape(3,6)
print(varr62)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [64]:
varr62[::-1,]

array([[12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [65]:
varr62[:,::-1]

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12]])

In [35]:
varr62[::-1,::-1]

array([[17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [36]:
varr67 = varr62.flatten()
varr67
print()
varr67[::-1]

array([17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,
        0])

In [37]:
varr62 = np.arange(9).reshape(3,3)
print(varr62)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
varr62

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
varr63 = np.flipud(varr62)
varr63

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [69]:
varr68 = varr63.ravel()
varr68[::-1]


array([2, 1, 0, 5, 4, 3, 8, 7, 6])

# Write a program to convert a string element to uppercase, lowercase, capitalise the first letter, title-case and swapcase of a given NumPy array.

In [70]:
arr = np.array(['i', 'love', 'NumPy', 'AND', 'interviewbit'], dtype=str)
print(arr)
print()
upper_case_arr = np.char.upper(arr)
lower_case_arr = np.char.lower(arr)
capitalize_case_arr = np.char.capitalize(arr)
titlecase_arr = np.char.title(arr)
swapcase_arr = np.char.swapcase(arr)

print("Upper Conversion: ", upper_case_arr)
print("Lower Conversion: ", lower_case_arr)
print("Capitalize First Letter Conversion: ", capitalize_case_arr)
print("Titlecase Conversion: ", titlecase_arr)
print("Swapcase Conversion: ", swapcase_arr)

['i' 'love' 'NumPy' 'AND' 'interviewbit']

Upper Conversion:  ['I' 'LOVE' 'NUMPY' 'AND' 'INTERVIEWBIT']
Lower Conversion:  ['i' 'love' 'numpy' 'and' 'interviewbit']
Capitalize First Letter Conversion:  ['I' 'Love' 'Numpy' 'And' 'Interviewbit']
Titlecase Conversion:  ['I' 'Love' 'Numpy' 'And' 'Interviewbit']
Swapcase Conversion:  ['I' 'LOVE' 'nUMpY' 'and' 'INTERVIEWBIT']


# Given a 4x4 Numpy matrix, how to reverse the matrix?

In [39]:
varr64 = np.arange(16).reshape(4,4)
print(varr64)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [41]:
varr107 = np.flipud(varr64)
varr107

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [43]:
varr108 = np.flip(varr64,axis = 1)
varr108                           

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [44]:
varr108 = np.flip(varr64,axis = 0)
varr108

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [46]:
varr108 = np.flip(varr64,axis = (0,1))
varr108

array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [72]:
varr64[::-1]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [73]:
varr64[:,::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [74]:
varr65 = varr64.flatten()
varr65

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [75]:
varr65[::-1]

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [76]:
varr66 = varr64.ravel()
varr66

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# How do you multiply two matrices?

In [77]:
varr67 = np.arange(9).reshape(3,3)
varr68 = np.arange(10,19).reshape(3,3)

In [78]:
print(varr67)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [79]:
print(varr68)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [80]:
varr69 = varr67.dot(varr68)
varr69

array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

# How to make a python function that handle scalers to work on numpy arrays?
convert the function maxx that works on two  scaler, two work on the two array

In [47]:
varr70 = np.array([4,5,6,7,8,9])
varr71 = np.array([5,7,8,3,2,6])

In [48]:
def maxx(varr70,varr71):
    if varr70 >= varr71:
        return varr70
    else:
        return varr71
pair_max = np.vectorize(maxx,otypes=[float]) 
pair_max(varr70,varr71)

array([5., 7., 8., 7., 8., 9.])

In [49]:
def maxx(varr70,varr71):
    if varr71 >= varr70:
        return varr71
    else:
        return varr70
pair_max = np.vectorize(min,otypes=[float]) 
pair_max(varr70,varr71)

array([4., 5., 6., 3., 2., 6.])

# swap columns 1 and 2 in array

In [50]:
varr72 = np.arange(9).reshape(3,3)
print(varr72)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [61]:
varr108 = np.swapaxes(varr72,0,1)
varr108

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [97]:
varr72[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# swap rows 1 and 2 in array

In [101]:
varr72[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [102]:
varr72[[2,0,1], :]

array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [103]:
varr72[[2,1,0], :]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# reverse the rows of 2d  array

In [105]:
varr73 = varr72.flatten()
varr73

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [106]:
varr73[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [109]:
varr74 = varr73[::-1].reshape(3,3)
varr74

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [110]:
varr72[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# reverse theb columns  of 2d  array

In [112]:
varr72[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# create 2D array of shape 5*3 to contains random  decimal  number between 5 & 10

In [51]:
varr75 = np.random.randint(low = 5, high = 10, size = (5,3))
print(varr75)
print()
varr76 = varr75 + np.random.random((5,3))
print(varr76)

[[7 9 8]
 [5 6 7]
 [8 8 8]
 [6 9 6]
 [5 8 6]]

[[7.5434459  9.93004971 8.54103223]
 [5.41052292 6.51660913 7.92844213]
 [8.27151732 8.94623653 8.72483995]
 [6.6533692  9.71959081 6.69742495]
 [5.95839557 8.60805137 6.10228249]]


# print or show only 3 decimal place in numpy array

In [52]:
varr78 = np.random.random((5,3))
varr78

array([[0.8515782 , 0.79437305, 0.21651134],
       [0.9986124 , 0.24453425, 0.53549709],
       [0.48512895, 0.46839319, 0.37269819],
       [0.92725781, 0.58723655, 0.4765325 ],
       [0.70752949, 0.07476234, 0.04772788]])

In [65]:
varr79 = np.random.random([5,3])
varr79

array([[4.23144746e-01, 2.65727312e-01, 1.26217527e-01],
       [4.84958580e-01, 9.52304909e-01, 2.34189113e-01],
       [9.30070214e-01, 2.68879541e-01, 9.41640941e-01],
       [7.55701526e-01, 4.68724532e-02, 6.32278673e-01],
       [2.27860659e-04, 1.40588674e-01, 1.97798920e-01]])

In [66]:
varr80 = np.around(varr78,decimals=3)
varr80

array([[0.852, 0.794, 0.217],
       [0.999, 0.245, 0.535],
       [0.485, 0.468, 0.373],
       [0.927, 0.587, 0.477],
       [0.708, 0.075, 0.048]])

# max

In [68]:
ar = np.max(varr80)
ar

0.999

In [69]:
ar = np.min(varr80)
ar

0.048

# second method

In [178]:
varr81 = np.random.random([5,3])
np.set_printoptions(precision=3)
varr81

array([[0.333, 0.748, 0.123],
       [0.774, 0.351, 0.444],
       [0.752, 0.973, 0.575],
       [0.492, 0.601, 0.768],
       [0.947, 0.142, 0.36 ]])

In [182]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [183]:
arr[1,2]

8

In [185]:
arr[::-1]

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [186]:
arr.shape

(2, 5)